import type { Metadata } from "next";
import "./globals.css";
import Providers from "../components/providers";
import { Toaster } from "sonner";
import { Geist } from "next/font/google";

const font = Geist({
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`bg-background max-w-lg mx-auto ${font.className}`}>
          {children}
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
